apps/course_sessions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.home_redirect, name='home'),
    url(r'^(?P<co_id>\d+)$', views.index, name='index_pattern'),
    url(r'^(?P<co_id>\d+)/(?P<filter_kw>\w+)$', views.index, name='index_filter'),
    url(r'^sesh/(?P<pk>\d+)$', views.SessionDetailView.as_view(), name='details'),
    url(r'^update_session$', views.update_session, name='update_session')
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login$', views.login_instructor, name='login'),
    url(r'^log_out$', views.log_out, name='log_out'),
]

apps/students/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.StudentsView.as_view(), name='index'),
    url(r'^(?P<filter>\w+)$', views.StudentsView.as_view(), name='index_filter'),
    url(r'^get_students/(?P<filter>\w+)$', views.GetStudents.as_view()), #edit this shit
    url(r'^s/(?P<pk>\d+)$', views.StudentDetailsView.as_view(), name='details'),
    url(r'^s/update/(?P<pk>\d+)$', views.UpdateStudentView.as_view(), name='update'),
    url(r'^s/(?P<pk>\d+)/create_alias$', views.create_alias, name='create_alias'),
    url(r'^s/(?P<pk>\d+)/create_note$', views.create_note, name='create_note'),
]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^sessions/', include('apps.course_sessions.urls', namespace='sessions')),
    url(r'^students/', include('apps.students.urls', namespace='students'))
]

shared/templates/footer.html
        </div>
    </body>
</html>

shared/templates/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load staticfiles %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" media="screen">
		<link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen">
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    </head>
    <body>
        <div class="container">

shared/templates/nav.html
<nav class="nav-style">
    <ul>
        <li><a href="{% url 'sessions:home' %}">Home</a></li>
        <li><a href="{% url 'students:index' %}">Students</a></li>
        <li><a href="{% url 'sessions:index' %}">Sessions</a></li>
        <li><a href="{% url 'login:log_out' %}">Logout</a></li>
    </ul>
</nav>