apps/students/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.StudentsView.as_view(), name='index'),
    url(r'^(?P<filter>\w+)$', views.StudentsView.as_view(), name='index_filter'),
    url(r'^get_students/(?P<filter>\w+)$', views.GetStudents.as_view()), #edit this shit
    url(r'^s/(?P<pk>\d+)$', views.StudentDetailsView.as_view(), name='details'),
    url(r'^s/update/(?P<pk>\d+)$', views.UpdateStudentView.as_view(), name='update'),
    url(r'^s/(?P<pk>\d+)/create_alias$', views.create_alias, name='create_alias'),
    url(r'^s/(?P<pk>\d+)/create_note$', views.create_note, name='create_note'),
]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^sessions/', include('apps.course_sessions.urls', namespace='sessions')),
    url(r'^students/', include('apps.students.urls', namespace='students'))
]

apps/students/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..course_sessions.models import Session, Cohort
from ..login.models import Instructor

# might consider making this a query set class rather than manager
class StudentManager(models.Manager):
    def student_filter(self, **kwargs):
        if str(kwargs['filter']) != 'all':
            return self.filter(status=str(kwargs['filter']))
        return self.all()

    def add_to_session(self, data):
        students = data.getlist('to_assign')
        sesh_id = int(data['session'])
        co_id = int(data['cohort_id'])
        for s in students:
            student = self.get(id=s)

            # remove sessions that conflict with new session start date
            conflict = student.session_history.filter(start_date_id=co_id).first()
            if conflict:
                student.session_history.remove(conflict)

            student.session_history.add(sesh_id)

    def assignment_filter(self, filter_kw, start_id):
        return self.filter(session_history__start_date_id = start_id).filter(status='active') \
            if str(filter_kw) == "assigned" else \
            self.exclude(session_history__start_date_id = start_id).filter(status='active')

    


class Student(models.Model):
    ACTIVE = 'active'
    PAUSED = 'paused'
    DROPPED = 'dropped'
    GRADUATED = 'graduated'

    STATUS_CHOICES = (
        (ACTIVE, "Active"),
        (PAUSED, "Paused"),
        (DROPPED, "Dropped"),
        (GRADUATED, "Graduated")
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    status = models.CharField(
        choices=STATUS_CHOICES,
        default=ACTIVE,
        max_length=20
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    starting_cohort = models.ForeignKey(Cohort)
    session_history = models.ManyToManyField(Session, related_name='students', blank=True)

    def last_session(self):
        return self.session_history.last()

    def session_in_start_date(self, sesh_start_id):
        return self.session_history.filter(start_date_id=sesh_start_id).first()

    def has_rolled_back(self):
        sesh_dict = {}
        for sesh in self.session_history.all():
            print sesh
            try:
                sesh_dict[sesh.course.id]
                return sesh_dict[sesh.course.id]
            except KeyError:
                sesh_dict[sesh.course.id] = True                
        return False

    # def save(self, **kwargs):
    #     super(Student, self).save(**kwargs)
    
    def __unicode__(self):
        return self.email

    objects = StudentManager()

class Alias(models.Model):
    handle = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    student = models.ForeignKey(Student, related_name='aliases')

class Note(models.Model):
    content = models.TextField()
    student = models.ForeignKey(Student, related_name='notes')
    created_at = models.DateTimeField(auto_now=True)
    instructor = models.ForeignKey(Instructor)

apps/students/forms.py
from django.forms import ModelForm
from django import forms
from ..course_sessions.models import Session
from .models import Student, Alias, Note
class CreateStudentForm(ModelForm):

    class Meta:
        model = Student
        fields = (
            'first_name',
            'last_name',
            'email',
            'starting_cohort'
        )

class UpdateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        print 'being initiated'
        student = kwargs['instance']
        try:
            q = Session.objects.filter(students=student)
        except KeyError:
            q = Session.objects.all()
        super(UpdateStudentForm, self).__init__(*args, **kwargs)
        self.fields['session_history'] = forms.ModelMultipleChoiceField(
            required=False, 
            widget=forms.CheckboxSelectMultiple,
            queryset = q
        )
    # def clean_session_history(self):
    #     print self.instance.session_history.all()
    #     print self.cleaned_data['session_history']
    
class CreateAliasForm(ModelForm):
    class Meta:
        model = Alias
        fields = ('source', 'handle')

class CreateNoteForm(ModelForm):
    content = forms.CharField(
        min_length=5, 
        label = "Leave a Note",
        widget=forms.Textarea()
    )
    class Meta:
        model = Note
        fields = ('content',)

apps/students/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.cache import cache
from django.views.generic import View, DetailView, UpdateView
from django.template.loader import render_to_string
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .forms import CreateStudentForm, CreateAliasForm, CreateNoteForm, UpdateStudentForm
from .view_helpers import set_context
from .models import Student
from django.contrib.auth.decorators import login_required

INDEX_TEMPLATE = 'students/index.html'
DETAILS_TEMPLATE = 'students/student_detail.html'
STUDENT_TABLE_TEMPLATE = 'students/student_table_partial.html'
DEFAULT_STUDENT_FILTER = 'active'
STUDENTS_CACHE_KEY = "all_students"

class StudentsView(LoginRequiredMixin, View):
    def get(self, req, filter=DEFAULT_STUDENT_FILTER):

        #helper function to initialize context with correct filter query on students
        context = set_context(filter)

        return render(req, INDEX_TEMPLATE, context)

    def post(self, req, filter):
        context = set_context(filter)
        form = CreateStudentForm(req.POST)
        if form.is_valid():
            form.save()

            #Update cache after adding a new sutdent model
            Student.objects.update_student_cache()
            
            return HttpResponseRedirect(reverse("students:index"))
        return render(req, INDEX_TEMPLATE, context)        
        context["form"] = form

class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = UpdateStudentForm
    template_name = 'students/student_update.html'

    def get_success_url(self):
        return reverse("students:details", kwargs={'pk':self.get_object().id})

    def form_valid(self, form):
        instance = form.save(commit=False)
        print form.data, 'is form'
        return super(UpdateStudentView, self).form_valid(form)
    # def post(self, req, pk):
    #     form = UpdateStudentForm(req.POST)
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect(reverse("students:show", kwargs={'pk':pk}))
    #     return render(req, self.template_name)

    # def get_context_data(self, *args, **kwargs):
    #     print self
    #     context = super(UpdateStudentView, self).get_context_data(*args, **kwargs)
    #     return context

class StudentDetailsView(LoginRequiredMixin, DetailView):
    model = Student
    def get_context_data(self, *args, **kwargs):
        context = super(StudentDetailsView, self).get_context_data(*args, **kwargs)
        context['alias_form'] = CreateAliasForm()
        context['note_form'] = CreateNoteForm()
        return context

    def post(self, req, pk):
        context = {
            "student": Student.objects.get(pk=pk)
        }
        print pk
        form = CreateAliasForm(req.POST)
        if form.is_valid():
            alias = form.save(commit=False)
            alias.student_id = pk
            alias.save()
        else:
            context["alias_form"] = CreateAliasForm(req.POST)

            return render(req, DETAILS_TEMPLATE, context)
        return HttpResponseRedirect(reverse("students:details", kwargs={'pk':pk}))

class GetStudents(LoginRequiredMixin, View):
    def get(self, req, filter=DEFAULT_STUDENT_FILTER):

        #helper function to initialize context with correct filter query on students
        context = set_context(filter)
        partial = render_to_string(STUDENT_TABLE_TEMPLATE, context)
        return HttpResponse(partial)

def create_alias(req, pk):
    if req.POST:
        context = {
            "student": Student.objects.get(pk=pk),
            "note_form": CreateNoteForm()
        }
        form = CreateAliasForm(req.POST)
        if form.is_valid():
            alias = form.save(commit=False)
            alias.student_id = pk
            alias.save()
        else:
            context["alias_form"] = form
            return render(req, DETAILS_TEMPLATE, context)
        return HttpResponseRedirect(reverse("students:details", kwargs={'pk':pk}))

def create_note(req, pk):
    if req.POST:
        context = {
            "student": Student.objects.get(pk=pk),
            "alias_form": CreateNoteForm()
        }
        form = CreateNoteForm(req.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.student_id = pk
            note.instructor_id = req.user.id
            note.save()
        else:
            context["note_form"] = form
            return render(req, DETAILS_TEMPLATE, context)
        return HttpResponseRedirect(reverse("students:details", kwargs={'pk':pk}))

apps/students/templates/students/index.html
{% include "templates/header.html" %}
{% include "templates/nav.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'students/css/student_style.css' %}" media="screen">
<h1>Students</h1>
<div class="student-manager">
    <ul class="filter-tab-list">
        <li><button class="filter-button" filter="active">Active</button></li>
        <li><button class="filter-button" filter="paused">Paused</button></li>
        <li><button class="filter-button" filter="dropped">Dropped</button></li>
        <li><button class="filter-button" filter="all">All</button></li>
    </ul>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Current Session</th>
                <th>Cohort Start Date</th>
            </tr>
        </thead>
        <tbody id="student-table">
        <!-- Content to be filled by partial -->
        {% include "students/student_table_partial.html" %}
        </tbody>
    </table>
</div>
<hr>
<h2>Add Student</h2>
<form action="{% url 'students:index_filter' filter %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Student">
</form>
{% include "templates/footer.html" %}

<script>
//Default AJAX Get method
function AjaxGet(url, callback) {
  let http = new XMLHttpRequest();
  http.onreadystatechange = () => {
    if (http.readyState === XMLHttpRequest.DONE && http.status === 200) {
        callback(http);
    } else if (http.status != 200 && http.status != 0) {
        console.log("Error: Request returned with error code " + http.status);
        console.log(http.responseText);
    }
  }
  http.open('GET', url, true);
  http.send();
}

function updatedStudentsTable(url){
    AjaxGet(url, (xmlHttp) => {
        //Take the response html and add it to the table body
        let tableContent = document.getElementById("student-table");
        tableContent.innerHTML = xmlHttp.responseText;
    })
}

//On click of a differnt filter button retreive student info
let filterButtons = document.getElementsByClassName("filter-button");
console.log(filterButtons);
Array.from(filterButtons).forEach((button) => {
    button.addEventListener('click', (e) => {
        filterStr = e.srcElement.attributes["filter"].value;
        url = "get_students/"; //Need to refactor this to not be absolute
        url += filterStr;
        updatedStudentsTable(url);
    }, false);
})

//Immediately invoke call to get all Active students
updatedStudentsTable("get_students/active");
</script>

apps/students/templates/students/student_create_form.html
<form action="{% url 'students:index' %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add Student" />
</form>

apps/students/templates/students/student_detail.html
{% include "templates/header.html" %}
{% include "templates/nav.html" %}
{% load student_session_tags %}

{% load staticfiles %}
<link rel="stylesheet" href="{% static 'students/css/student_style.css' %}" media="screen">

{% current_session_id as curr_sesh_id %}
{% assigned_session student.id curr_sesh_id as current_session %}
{% assigned_session student.id curr_sesh_id 'next' as next_session %}
<div class="info-block">
    <h2>{{ student.first_name }} {{ student.last_name }}</h2>
    <h4>{{ student.email }}</h4>
    <a href="{% url 'students:update' student.id %}"><button>Edit Student</button></a>
</div>
<ul class="info-block">
    <li><strong>Status:</strong> {{ student.status }}</li>
    {% if current_session %}
    <li><strong>Current Session:</strong> <a href="{% url 'sessions:details' current_session.id %}">{{ current_session }}</a></li>
    {% else %}
    <li><strong>Current Session:</strong> {{ current_session }}</li>
    {% endif %}
    {% if next_session %}
    <li><strong>Next Session:</strong> <a href="{% url 'sessions:details' next_session.id %}">{{ next_session }}</a></li>
    {% else %}
    <li><strong>Next Session:</strong> {{ next_session }}</li>
    {% endif %}
    <li><strong>Used Rollback</strong> {{ student.has_rolled_back }}</li>
</ul>
<hr>
<div class="info-block">
    <h4>Session History</h4>
    <ul id='sesh-history'>
        {% for session in student.session_history.all %}
        <li><a href="{% url 'sessions:details' session.id %}">{{ session }}</a></li>
        {% endfor %}
    </ul>
</div>
<div class="info-block">
    <h4>Aliases</h4>
    <ul>
        {% for alias in student.aliases.all %}
        {% if alias.source|lower == 'github' %}
            <li><strong>{{ alias.source }}</strong> <a href="http://github.com/{{ alias.handle }}">{{ alias.handle }}</a></li>        
        {% else %}
            <li><strong>{{ alias.source }}</strong> {{ alias.handle }}</li>
        {% endif %}
        {% endfor %}
    </ul>
    <h5>Add Alias</h5>
    <form action="{% url 'students:create_alias' student.id %}" method="POST"\>{% csrf_token %}
        {{ alias_form.as_p }}
        <input type="submit" value="Add Alias">
    </form>
</div>
<form id='note-form' action="{% url 'students:create_note' student.id %}" method="POST"\>{% csrf_token %}
    {{ note_form }}
    <input type="submit" value="Add Note">
</form>
<div class='notes'>
    {% for note in student.notes.all %}
        <div class="note">
            <h5>{{note.content}}</h5>
            <h6>Noted By:<strong> {{ note.instructor.first_name }} {{ note.instructor.last_name }} </strong>({{ note.created_at }})</h6>
        </div>
    {% endfor %}
</div>
{% include "templates/footer.html" %}

apps/students/templates/students/student_table_partial.html
{% for student in students %}
<tr>
    <td><a href="{% url 'students:details' student.id %}">{{ student.first_name }} {{ student.last_name }}</a></td>
    <td>{{ student.last_session }}</td>
    <td>{{ student.starting_cohort }}</td>
</tr>
{% endfor %}

apps/students/templates/students/student_update.html
{% include "templates/header.html" %}
{% include "templates/nav.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'students/css/student_style.css' %}" media="screen">

<form action='{% url "students:update" student.id %}' method="POST">{% csrf_token %}
    {% for field in form %}
    {% if field.errors %}
        {% for error in field.errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
    {% endif %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field }}
    </div>
    {% endfor %}
    <hr>
    <input type="submit" value="Update">
</form>
<a href="{% url 'students:details' student.id %}"><button>Cancel</button></a>
{% include "templates/footer.html" %}