apps/course_sessions/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home$', views.home_redirect, name='home'),
    url(r'^(?P<co_id>\d+)$', views.index, name='index_pattern'),
    url(r'^(?P<co_id>\d+)/(?P<filter_kw>\w+)$', views.index, name='index_filter'),
    url(r'^sesh/(?P<pk>\d+)$', views.SessionDetailView.as_view(), name='details'),
    url(r'^update_session$', views.update_session, name='update_session')
]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^sessions/', include('apps.course_sessions.urls', namespace='sessions')),
    url(r'^students/', include('apps.students.urls', namespace='students'))
]

apps/course_sessions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.utils.timezone import now
from ..login.models import Instructor

class CohortManager(models.Manager):
    def current_cohort_id(self):
        #TODO(dev): current implementation here required at least one instace of Cohort
        #or app will break.  This can be done in /admin, but thats a lil janky (but do we care?)
        try:
            results = self.filter(starting_date__lt = now()).last().id
        except:
            results = None
        return results
        
    def previous_cohort(self, id):
        this_cohort_starts = self.get(id=id).starting_date
        return self.filter(starting_date__lt = this_cohort_starts).last()
    def next_cohort(self, id):
        this_cohort_starts = self.get(id=id).starting_date        
        return self.filter(starting_date__gt = this_cohort_starts).first()
    def adjacent_cohort(self, id, ajacency):
        if ajacency == 'next':
            return self.next_cohort(id)
        return self.previous_cohort(id)

class SessionManager(models.Manager):
    def users_current_session_or_none(self, user_id, start_date_id):
        return self.filter(start_date=start_date_id).filter(instructor=user_id).first()
        

class Cohort(models.Model):
    starting_date = models.DateTimeField()
    def __unicode__(self):
        return str(self.starting_date.strftime('%B %d, %Y'))
    class Meta:
        ordering = ['starting_date']
    objects =  CohortManager()

class ParentCourse(models.Model):
    name = models.CharField(max_length=100)
    def __unicode__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=100, unique=True)
    lecture_link = models.CharField(max_length=100)
    parent = models.ForeignKey(ParentCourse)
    def __unicode__(self):
        return self.name

class Session(models.Model):
    start_date = models.ForeignKey(Cohort)
    course = models.ForeignKey(Course)
    instructor = models.ForeignKey(Instructor, related_name="sessions")
    objects = SessionManager()
    def __unicode__(self):
        return "{} ({})".format(self.course, self.start_date.starting_date.strftime("%m/%d/%Y")) 
    

apps/course_sessions/forms.py
from django import forms
from .models import Session
class EmailStudentsInSessionForm(forms.Form):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows':50, 'cols':50}
        )
    )
    password = forms.CharField(
        label="Your Dojo Mail Password",
        widget=forms.PasswordInput
    )
    # fields = ('message', 'password')
    # class Meta:
        # model = Session
    # def __init__(self, *args, **kwargs):
    #     print "being inistanitaed"
    #     super(self, EmailStudentsInSessionForm).__init__(*args, **kwargs)

apps/course_sessions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..students.models import Student
from .models import Session, Cohort, Course
from django.contrib import messages
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, reverse, HttpResponse
from django.apps.registry import apps

MAIN_TEMPLATE = 'course_sessions/index.html'

@login_required
def home_redirect(req):
    sesh = Session.objects.users_current_session_or_none(req.user.id, Cohort.objects.current_cohort_id())
    if sesh:
        return HttpResponseRedirect(reverse("sessions:details", kwargs={"pk": sesh.id}))
    return HttpResponseRedirect(reverse("sessions:index"))

@login_required
# this view will default to show sessions for the 'current' cohort
def index(req, co_id=Cohort.objects.current_cohort_id(), filter_kw="unassigned"):
    try:
        prev_id = Cohort.objects.previous_cohort(co_id).id
    except:
        prev_id = None
    try:
        next_id = Cohort.objects.next_cohort(co_id).id
    except:
        next_id = None
    
    context = {
        "students": Student.objects.assignment_filter(filter_kw, co_id),
        "session_start": Cohort.objects.get(id=co_id),
        "sessions": Session.objects.filter(start_date_id=co_id),
        "prev_id": prev_id,
        "next_id": next_id,
        "ass_filter": ["unassigned", "assigned"]
    }
    return render(req, MAIN_TEMPLATE, context)

class SessionDetailView(LoginRequiredMixin, DetailView):
    model = Session

def update_session(req):
    try: 
        req.POST.getlist('to_assign')
        Student.objects.add_to_session(req.POST)
    except KeyError:
        messages.error(req, "Please select a student to add")
        context = {
            "students": Student.objects.filter(status='active'),
            "start_dates": Cohort.objects.all(),
            "courses": Course.objects.all()
        }
        return render(req, MAIN_TEMPLATE, context)
    return HttpResponseRedirect(reverse("sessions:index"))

apps/course_sessions/templates/course_sessions/date_picker_old.html
<label for="start_date">Select a Start Date</label>
<select id='date' name='session'>
    {% for date in session_start %}
    {% if date.id == this_date_id %}
    <option selected value="{{date.id}}">{{ date }}</option>
    {% else %}
    <option value="{{date.id}}">{{ date }}</option>
    {% endif %}
    {% endfor %}
</select>

apps/course_sessions/templates/course_sessions/index.html
{% include "templates/header.html" %}
{% include "templates/nav.html" %}
{% load student_session_tags %}
{% load staticfiles %}
<h1>Manage Sessions for {{ session_start }}</h1>
<span>{% if prev_id %}<a href="{% url 'sessions:index_pattern' prev_id %}">Prev</a>{% endif %} | {% if next_id %}<a href="{% url 'sessions:index_pattern' next_id %}">Next</a>{% endif %}</span>
<form action='{% url "sessions:update_session" %}' method="POST">{% csrf_token %}
    <label for="start_date">Select a Session</label>
    <select onchange="updateLink()" id='session-picker' name='session'>
        {% for sesh in sessions %}
        <option value="{{sesh.id}}">{{ sesh }}</option>
        {% endfor %}
    </select>
    <input type="hidden" name='cohort_id' value='{{ session_start.id }}'>
    <ul class="filter-tab-list">
        <li><a href="{% url 'sessions:index_filter' session_start.id ass_filter.0 %}">Unassigned</a></li>
        <li><a href="{% url 'sessions:index_filter' session_start.id ass_filter.1 %}">Assigned</a></li>
    </ul>
    {% if messages %}
        {% for m in messages %}
        <p>{{ m }}</p>
        {% endfor %}
    {% endif %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Currently Assigned</th>
                <th>Assign</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <!--see custom template tag @ templatetags/student_session_tags-->
                {% assigned_session student.id session_start.id as student_session %}
                <td><a href="{% url 'students:details' student.id %}">{{ student.first_name }} {{ student.last_name }}</a></td>
                {% if student_session != None %}
                <td><a href="{% url 'sessions:details' student_session.id %}">{{ student_session }}</a></td>
                {% else %}
                <td>None</td>                
                {% endif %}
                <td><input type="checkbox" name="to_assign" value="{{ student.id }}"></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if sessions|length > 0 %}
    <input type="submit" value="Assign Student(s)">
    {% endif %}
</form>
{% if sessions|length > 0 %}
    <hr>
    <h2>Sessions This Month</h2>
    <table>
        <thead>
            <tr>
                <th>Course</th>
                <th>Instructor</th>
                <th>Number of Students</th>
            </tr>
        </thead>
        <tbody>
            {% for sesh in sessions %}
            <tr>
                <td><a href="{% url 'sessions:details' sesh.id %}">{{ sesh.course.name }}</a></td>
                <td>{{ sesh.instructor.first_name }} {{ sesh.instructor.last_name }}</td>
                <td>{{ sesh.students.all | length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}
<!-- <script src="{% static 'course_sessions/js/choose_selected_session.js' %}"></script> -->

{% include "templates/footer.html" %}

apps/course_sessions/templates/course_sessions/session_detail.html
{% include "templates/header.html" %}
{% include "templates/nav.html" %}
{% load student_session_tags %}
<h1>{{ session.course }}</h1>
<ul class="detail-list">
    <li><strong>Instructor: </strong>{{ session.instructor.first_name }} {{ session.instructor.last_name }}</li>
    <li><strong>Start Date: </strong>{{ session.start_date }}</li>
    <li><strong>Lecture Link: </strong><a href="{{session.course.lecture_link}}">{{ session.course.lecture_link }}</a></li>
</ul>
<h3>Students in Session</h3>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Next Session</th>
            <th>Started Program</th>
        </tr>
    </thead>
    <tbody>
        {% for student in session.students.all %}
        <tr>
            <td><a href="{% url 'students:details' student.id %}">{{ student.first_name }} {{ student.last_name }}</a></td>
            <td>{{ student.email }}</td>
            <td>{% assigned_session student.id session.start_date.id 'next' %}</td>
            <td>{{ student.starting_cohort }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
<h4>Email Students</h4>
<form action='{% url "sessions:email_students" session.id %}' method="POST">{% csrf_token %}
    {{ email_form }}
    <input type="submit" value="Send">
</form>
{% include "templates/footer.html" %}